// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnz3m2_V0TXmyKVAnZ9OqdTXjchor2ZQ',
    appId: '1:346888638520:web:2bf1d8c69572a9e68b16cd',
    messagingSenderId: '346888638520',
    projectId: 'fir-project-cbcef',
    authDomain: 'fir-project-cbcef.firebaseapp.com',
    storageBucket: 'fir-project-cbcef.firebasestorage.app',
    measurementId: 'G-RKE90JSPPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCau1fMgP3YMxjZNTJlF7h3sN4GPwlomiE',
    appId: '1:346888638520:android:fd7fef579622a9e18b16cd',
    messagingSenderId: '346888638520',
    projectId: 'fir-project-cbcef',
    storageBucket: 'fir-project-cbcef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ewMn8MfA8iTAlcQmAg08GpINQ5E9fo4',
    appId: '1:346888638520:ios:836911b378aa85478b16cd',
    messagingSenderId: '346888638520',
    projectId: 'fir-project-cbcef',
    storageBucket: 'fir-project-cbcef.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ewMn8MfA8iTAlcQmAg08GpINQ5E9fo4',
    appId: '1:346888638520:ios:836911b378aa85478b16cd',
    messagingSenderId: '346888638520',
    projectId: 'fir-project-cbcef',
    storageBucket: 'fir-project-cbcef.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

}